version: '3.9'

services:
  db:
    image: postgres:15
    container_name: scheduler_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.example.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: scheduler_backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:pass@db:5432/mydb
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: scheduler_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app
